#!/bin/sh
#
# Configure options script for re-calling GraphicsMagick compilation
# options required to use the GraphicsMagick library.
#
# Concept derived from gtk-config in the Gtk package except that Autoconf-style
# configuration information is presented instead so that it may be used more
# effectively in configure scripts.
#
usage='Usage: GraphicsMagick-config [--cflags] [--cppflags] [--exec-prefix] [--ldflags] [--libs] [--prefix] [--version]

 For example, "example.c" may be compiled to produce "example" as follows:

  "gcc -o example example.c `GraphicsMagick-config --cppflags --cflags --ldflags --libs`"'

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case $1 in
    --prefix)
      echo /usr/local
      ;;
    --exec-prefix)
      echo /usr/local
      ;;
    --version)
      echo 1.3.25
      ;;
    --cflags)
      echo '-g -O2 -Wall -pthread'
      ;;
    --cppflags)
      echo '-I/usr/local/include/GraphicsMagick'
      ;;
    --ldflags)
      echo '-L/usr/local/lib -L/home/jake/git_stuff/LLVMdir/libFuzzer.a'
      ;;
    --libs)
      echo '-lGraphicsMagick -lXext -lX11 -lxml2 -lz -lm -lpthread'
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

